### ISSUE TITLE
No location authorization set by delegate

### ISSUE THREAD

**Issue by tuuky** [himbeles/LocationProvider#3] opened 2020-08-21 03:25 UTC
Hey Luis, I'm getting the error you print "No location authorization status set by delegate yet" in my SwiftUI view model using your LocationProvider.

`@ObservedObject var locationProvider: LocationProvider

// in my init, I do this:

locationProvider = LocationProvider()
        do {
            try locationProvider.start()
        } catch {
            print("location provider could not start")
            locationProvider.requestAuthorization()
        }
`

But the location provider is nil
I'm running it on a device and I've allowed location services
Any help would be appreciated it

I've updated it to get the location on my view and I'm still getting the same error. I instatiate and call start in init() like you show and onAppear I try to pass the location info to my viewmodel, but the location is always nil. I added some logs to see if my location was being updated and it is, but no luck getting that info in my view :/

**Comment by himbeles** [comment] 2020-08-21 12:30
Hi Rob, 
Thanks for the feedback! 
Currently on holiday, but I'll get back to you when I'm back.

**Comment by himbeles** [comment] 2020-08-21 12:34
Have you set the appropriate permissions in the App's .plist file?

**Comment by himbeles** [comment] 2020-09-14 18:45
Hi Rob, if you still have this issue, would you mind posting the full stack trace of the error?

**Comment by himbeles** [comment] 2020-09-18 07:09
Closing because of missing feedback and not being able to reproduce.

**Closed as completed by himbeles** 2020-09-18 07:09 UTC
